export const GalleryData = [
    {
        id:1,
        title:"noxus",
        image:"./images/noxus1.jpg"
    },
    {
        id:2,
        title:"noxus",
        image:"./images/noxus2.jpg"
    },
    {
        id:3,
        title:"noxus",
        image:"./images/noxus3.jpg"
    },
    {
        id:4,
        title:"noxus",
        image:"./images/noxus4.jpg"
    },
    {
        id:5,
        title:"demacia",
        image:"./images/demacia1.jpg"
    },
    {
        id:6,
        title:"demacia",
        image:"./images/demacia2.jpg"
    },
    {
        id:7,
        title:"demacia",
        image:"./images/demacia3.jpg"
    },
    {
        id:8,
        title:"demacia",
        image:"./images/demacia4.jpg"
    },
    {
        id:9,
        title:"freljord",
        image:"./images/freljord1.jpg"
    },
    {
        id:10,
        title:"freljord",
        image:"./images/freljord2.jpg"
    },
    {
        id:11,
        title:"freljord",
        image:"./images/freljord3.jpg"
    },
    {
        id:12,
        title:"freljord",
        image:"./images/freljord4.jpg"
    },
    {
        id:13,
        title:"ionia",
        image:"./images/ionia1.jpg"
    },
    {
        id:14,
        title:"ionia",
        image:"./images/ionia2.jpg"
    },
    {
        id:15,
        title:"ionia",
        image:"./images/ionia3.jpg"
    },
    {
        id:16,
        title:"ionia",
        image:"./images/ionia4.jpg"
    },
    {
        id:17,
        title:"biglewater",
        image:"./images/biglewater1.jpg"
    },
    {
        id:18,
        title:"biglewater",
        image:"./images/biglewater2.jpg"
    },
    {
        id:19,
        title:"biglewater",
        image:"./images/biglewater3.jpg"
    },
    {
        id:20,
        title:"biglewater",
        image:"./images/biglewater4.jpg"
    },
    {
        id:21,
        title:"piltover",
        image:"./images/piltover1.jpg"
    },
    {
        id:22,
        title:"piltover",
        image:"./images/piltover2.jpg"
    },
    {
        id:23,
        title:"piltover",
        image:"./images/piltover3.jpg"
    },
    {
        id:24,
        title:"piltover",
        image:"./images/piltover4.jpg"
    },
    {
        id:25,
        title:"shadowisles",
        image:"./images/shadowisles1.jpg"
    },
    {
        id:26,
        title:"shadowisles",
        image:"./images/shadowisles2.jpg"
    },
    {
        id:27,
        title:"shadowisles",
        image:"./images/shadowisles3.jpg"
    },
    {
        id:28,
        title:"shadowisles",
        image:"./images/shadowisles4.jpg"
    },
    {
        id:29,
        title:"zaun",
        image:"./images/zaun1.jpg"
    },
    {
        id:30,
        title:"zaun",
        image:"./images/zaun2.jpg"
    },
    {
        id:31,
        title:"zaun",
        image:"./images/zaun3.jpg"
    },
    {
        id:32,
        title:"zaun",
        image:"./images/zaun4.jpg"
    },
]